### ISSUE TITLE
pysam 'pysam.calignmentfile.AlignedSegment' error using speedseq sv -g

### ISSUE THREAD

**Issue by djakubosky** [hall-lab/speedseq#105]
When using the genotyping -g parameter to speedseq sv (version cloned yesterday from github) there appears to be some type of pysam error during svtyper genotyping.  I have tried with pysam 0.8.3 and 0.11 (latest) and neither has fixed it.  I find that when using svtyper 0.1.3 to do this step manually, only the latter of the two versions will work.  Is there a specific version of pysam that is needed? any insights into this error?
Error:
'pysam.calignmentfile.AlignedSegment' object has no attribute 'reference_name'

**Comment by cc2qe** [comment]
I do agree that this is related to pysam. Do I understand correctly that using pysam v0.11.0 fixes the problem when running svtyper manually, but it does not fix the problem when running it through speedseq?

On a separate note, you should bump svtyper to v0.1.4 because it patches a small but potentially important issue with maximum sampling depth. The new version is already included in speedseq

**Comment by djakubosky** [comment]
Yes you understand correctly, I have the pysam 0.1.1 installed in its own anaconda env with the speedseq config pointing to this python install.  If I source activate this env and run svtyper 0.1.3 it will run without errors (including on the specific files produced from speeseq).

**Comment by djakubosky** [comment]
Thanks for the tip on the svtyper update! I want to note that running genotyping on its own works with svtyper 0.1.4 also, using pysam 0.1.1.  For now I will just proceed make individual genotyping jobs instead. 

Related to this: The newest svtools commands such as lsort and lmerge seem not to work with pysam 0.8.3 but do work with 0.1.1, just wanted to point that out too, might be good to flag in your svtools repo.

**Comment by cc2qe** [comment]
Ok thanks for the additional info. I can't really think of a good explanation for why speedseq would fail with the updated pysam unless there is some other python environment variable directing it to a different pysam version.

lsort and lmerge do not require pysam at all, but will update the svtools requirements because SVTyper (which is included) needs 0.8.4 or higher. Thanks for pointing this out

**Comment by djakubosky** [comment]
Thanks for the feedback. I noticed the svtyper version in svtools genotype is 0.1.2, is this an issue? do you suggest genotyping all sets of calls using 1.4?

**Comment by cc2qe** [comment]
0.1.2 should be fine. The only difference between 0.1.2 and 0.1.4 is an optional command line argument flag.
